### ISSUE TITLE
ios pod 时出现错误

### ISSUE THREAD

**Issue by Yunnathai** [imengyu/imengyu-ui-lib#1]
[!] The `RNIMengyuUILib` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `authors`.
    - WARN  | github_sources: Github repositories should end in `.git`.

**Comment by Yunnathai** [comment]
最新的版本跑起来了，但是UI有点简陋，能还原下vant的样式就好了。

**Comment by imengyu** [comment]
感谢你的支持，最新版修改了一些 iOS 上运行的问题。样式和vant很像了，但有一些自己的设计。这个库只是参考并不是vant-rn，也没有打算样式和vant一模一样。

**Comment by Yunnathai** [comment]
已经很不错了，致敬花的精力，期待一步步完善，star了。
